import { Geist, Geist_Mono } from "next/font/google";

import type { Metadata } from "next";

import { Sidebar } from "@/ui/Sidebar/Sidebar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{ display: "flex", height: "100vh" }}>
          <Sidebar></Sidebar>
          <div
            style={{
              width: "100%",
              height: "100vh",
              background: "#f5f4f7",
              display: "flex",
              flexDirection: "column",
              minHeight: "0",
              // overflow: "hidden",
            }}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
